{{- if .Values.vs.enabled | default false }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
    name: {{ template "trino.fullname" . }}
spec:
    gateways:
        - istio-ingress/internal-gateway
    hosts:
        - {{ .Release.Name }}.dview.io
    http:
        -   match:
                -   uri:
                        prefix: /
            route:
                -   destination:
                        host: {{ template "trino.fullname" . }}
                        port:
                            number: 8080  # Change this to match the service port
{{- end}}
