apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
    name: test-trino-virtual-svc
spec:
    gateways:
        - istio-ingress/internal-gateway
    hosts:
        - test-trino.default.dview.io
    http:
        -   match:
                -   uri:
                        prefix: /
            route:
                -   destination:
                        host: test-trino.default.svc.cluster.local
                        port:
                            number: 8080  # Change this to match the service port
